/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:4bcc5020-975f-49bd-9c03-f01c4e4cbebb",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_DDa6BFGE1",
    "aws_user_pools_web_client_id": "6heam849b87qtbki64rlak1s8l",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://tzewrwchunedbazroqqjy7sd34.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
